'use client';
import { useEffect, useState } from 'react';
import { formatPrice } from '@/lib/utils';

type Analytics = { periodRevenue:string; previousRevenue:string; revenueTrend:number; deliveredOrders:number; pendingOrders:number; topProducts:{id:string;name:string;quantity:number;revenue:string}[]; categoryRevenue:{category:string;revenue:string}[] };

export default function AnalyticsPage() {
  const [days,setDays]=useState(30); const [data,setData]=useState<Analytics|null>(null); const [error,setError]=useState('');
  useEffect(()=>{ setData(null); setError(''); fetch(`/api/seller/analytics?days=${days}`).then(async r=>{const b=await r.json(); if(!r.ok) throw new Error(b.error?.message??b.error??'Không tải được dữ liệu'); setData(b);}).catch(e=>setError(e instanceof Error?e.message:'Không tải được dữ liệu')); },[days]);
  return <div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:30}}><div><h1 style={{fontSize:28,fontWeight:800}}>Phân tích bán hàng</h1><p style={{color:'var(--text-muted)'}}>Dữ liệu thật, tách riêng theo shop và chỉ tính đơn đã giao.</p></div><select value={days} onChange={e=>setDays(Number(e.target.value))} className="input-field" style={{width:150}}><option value={7}>7 ngày</option><option value={30}>30 ngày</option><option value={90}>90 ngày</option></select></div>
    {error&&<div className="glass-card" style={{padding:20,color:'#ef4444'}}>{error}</div>}{!data&&!error&&<div className="glass-card" style={{padding:20}}>Đang tải...</div>}{data&&<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:20,marginBottom:30}}>{[['Doanh thu kỳ này',formatPrice(data.periodRevenue)],['Kỳ trước',formatPrice(data.previousRevenue)],['Tăng trưởng',`${data.revenueTrend>=0?'+':''}${data.revenueTrend}%`],['Đơn đã giao / chờ',`${data.deliveredOrders} / ${data.pendingOrders}`]].map(([l,v])=><div key={l} className="glass-card" style={{padding:20}}><small>{l}</small><h3 style={{color:'var(--accent)'}}>{v}</h3></div>)}</div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:24}}><div className="glass-card" style={{padding:24}}><h3>Top sản phẩm</h3>{data.topProducts.length===0?<p>Chưa có đơn giao thành công.</p>:data.topProducts.map(p=><div key={p.id} style={{display:'flex',justifyContent:'space-between',padding:'12px 0',borderBottom:'1px solid rgba(255,255,255,.08)'}}><span>{p.name}<small style={{display:'block'}}>{p.quantity} đã bán</small></span><b>{formatPrice(p.revenue)}</b></div>)}</div><div className="glass-card" style={{padding:24}}><h3>Doanh thu theo danh mục</h3>{data.categoryRevenue.length===0?<p>Chưa có dữ liệu.</p>:data.categoryRevenue.map(c=><div key={c.category} style={{display:'flex',justifyContent:'space-between',padding:'12px 0'}}><span>{c.category}</span><b>{formatPrice(c.revenue)}</b></div>)}</div></div></>}</div>;
}