import { Prisma } from '@prisma/client';
import { type NextRequest } from 'next/server';
import { z } from 'zod';
import prisma from '@/lib/db';
import { requireAdmin } from '@/lib/auth';
import { createHandler } from '@/lib/api-handler';
import { ConflictError, NotFoundError } from '@/lib/errors';
const schema=z.object({action:z.enum(['APPROVE','REJECT','COMPLETE'])}).strict();
export async function PATCH(req:NextRequest,context:{params:Promise<{id:string}>}){return createHandler(async request=>{const admin=await requireAdmin();const {id}=await context.params;const input=schema.parse(await request.json());return prisma.$transaction(async tx=>{const item=await tx.fulfillmentReturn.findUnique({where:{id},include:{fulfillment:{include:{orderItems:true,settlement:true,codCollection:true}}}});if(!item)throw new NotFoundError('Không tìm thấy yêu cầu trả hàng');const expected=input.action==='COMPLETE'?'APPROVED':'REQUESTED';if(item.status!==expected)throw new ConflictError('Trạng thái yêu cầu trả hàng không hợp lệ');const status=input.action==='APPROVE'?'APPROVED':input.action==='REJECT'?'REJECTED':'COMPLETED';if(status==='APPROVED'&&item.fulfillment.settlement?.status==='AVAILABLE')await tx.sellerSettlement.update({where:{id:item.fulfillment.settlement.id},data:{status:'HELD'}});if(status==='COMPLETED'&&item.fulfillment.settlement){await tx.sellerSettlement.update({where:{id:item.fulfillment.settlement.id},data:{status:item.fulfillment.settlement.status==='PAID'?'REVERSAL_REQUIRED':'REVERSED'}});if(item.fulfillment.codCollection)await tx.codCollection.update({where:{id:item.fulfillment.codCollection.id},data:{status:'REFUND_DUE'}});}if(status==='COMPLETED'){for(const orderItem of item.fulfillment.orderItems){await tx.$queryRaw(Prisma.sql`SELECT id FROM product WHERE id=${orderItem.productId} FOR UPDATE`);const before=await tx.product.findUniqueOrThrow({where:{id:orderItem.productId},select:{stockQuantity:true}});const after=before.stockQuantity+orderItem.quantity;await tx.product.update({where:{id:orderItem.productId},data:{stockQuantity:after,inStock:true}});await tx.inventoryMovement.create({data:{productId:orderItem.productId,actorId:admin.userId,type:'RETURN',quantityDelta:orderItem.quantity,stockBefore:before.stockQuantity,stockAfter:after,reason:'Fulfillment return completed',referenceType:'FulfillmentReturn',referenceId:id,idempotencyKey:`return:${id}:${orderItem.productId}`}});}}
return tx.fulfillmentReturn.update({where:{id},data:{status,...(status==='COMPLETED'?{completedAt:new Date()}:{decidedAt:new Date()})}});});})(req);}