'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { useToastStore } from '@/components/ui/Toast';
import { formatPrice } from '@/lib/utils';

type Voucher={id:string;code:string;description:string|null;discountType:string;discountValue:string;minOrderValue:string;maxDiscount:string|null;startDate:string;endDate:string;usageLimit:number;usedCount:number};
type Form={code:string;description:string;discountType:'percentage'|'fixed';discountValue:string;minOrderValue:string;maxDiscount:string;endDate:string;usageLimit:string};
const initial:Form={code:'',description:'',discountType:'percentage',discountValue:'',minOrderValue:'0',maxDiscount:'',endDate:'',usageLimit:'100'};
function message(body:unknown){if(typeof body==='object'&&body){const value=body as {error?:string|{message?:string};message?:string};return typeof value.error==='string'?value.error:value.error?.message??value.message??'Có lỗi xảy ra';}return 'Có lỗi xảy ra';}

export default function MarketingPage(){
 const [items,setItems]=useState<Voucher[]>([]); const [form,setForm]=useState<Form>(initial); const [show,setShow]=useState(false); const [loading,setLoading]=useState(true); const toast=useToastStore(s=>s.addToast);
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/seller/vouchers');const b=await r.json();if(!r.ok)throw new Error(message(b));setItems(b);}catch(e){toast(e instanceof Error?e.message:'Không tải được voucher','error');}finally{setLoading(false);}},[toast]);
 useEffect(()=>{void load();},[load]);
 async function create(e:FormEvent){e.preventDefault();const payload={...form,usageLimit:Number(form.usageLimit),maxDiscount:form.maxDiscount||null,currency:'VND'};const r=await fetch('/api/seller/vouchers',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok){toast(message(b),'error');return;}toast('Tạo voucher thành công');setForm(initial);setShow(false);void load();}
 async function remove(id:string){if(!confirm('Xóa voucher này?'))return;const r=await fetch(`/api/seller/vouchers/${id}`,{method:'DELETE'});const b=await r.json();if(!r.ok){toast(message(b),'error');return;}toast('Đã xóa voucher');void load();}
 async function reactivate(id:string){const r=await fetch(`/api/seller/vouchers/${id}/reactivate`,{method:'PUT',headers:{'content-type':'application/json'},body:'{}'});const b=await r.json();if(!r.ok){toast(message(b),'error');return;}toast('Đã gia hạn thêm 30 ngày');void load();}
 return <div><div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'center',marginBottom:30}}><div><h1 style={{fontSize:28,fontWeight:800}}>Voucher của shop</h1><p style={{color:'var(--text-muted)'}}>Voucher chỉ áp dụng cho sản phẩm thuộc Seller hiện tại.</p></div><button className="btn-primary" onClick={()=>setShow(true)}>+ Tạo voucher</button></div>
 {loading?<div className="glass-card" style={{padding:24}}>Đang tải...</div>:items.length===0?<div className="glass-card" style={{padding:24}}>Shop chưa có voucher.</div>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:20}}>{items.map(v=>{const expired=new Date(v.endDate)<new Date();return <div key={v.id} className="glass-card" style={{padding:22,borderLeft:`4px solid ${expired?'#ef4444':'var(--accent)'}`}}><div style={{display:'flex',justifyContent:'space-between'}}><div><h3 style={{margin:0}}>{v.code}</h3><small>{v.description||'Không có mô tả'}</small></div><b style={{color:expired?'#ef4444':'#10b981'}}>{expired?'HẾT HẠN':'ĐANG CHẠY'}</b></div><p style={{fontWeight:700,color:'var(--accent)'}}>{v.discountType==='percentage'?`${v.discountValue}%`:formatPrice(v.discountValue)} · đơn từ {formatPrice(v.minOrderValue)}</p><small>Đã dùng {v.usedCount}/{v.usageLimit} · Hết hạn {new Date(v.endDate).toLocaleDateString('vi-VN')}</small><div style={{display:'flex',gap:10,marginTop:16}}>{expired&&<button className="btn-secondary" onClick={()=>void reactivate(v.id)}>Gia hạn 30 ngày</button>}<button className="btn-secondary" onClick={()=>void remove(v.id)} style={{color:'#ef4444'}}>Xóa</button></div></div>;})}</div>}
 {show&&<div style={{position:'fixed',inset:0,zIndex:1000,background:'rgba(0,0,0,.8)',display:'grid',placeItems:'center',padding:20}}><form onSubmit={create} className="glass-card" style={{background:'#121212',width:'min(560px,100%)',padding:28,display:'grid',gap:14}}><h2 style={{margin:0}}>Tạo voucher mới</h2><input required className="input-field" placeholder="Mã voucher" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><input className="input-field" placeholder="Mô tả" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><select className="input-field" value={form.discountType} onChange={e=>setForm({...form,discountType:e.target.value as Form['discountType']})}><option value="percentage">Phần trăm</option><option value="fixed">Số tiền cố định</option></select><input required className="input-field" inputMode="numeric" placeholder="Giá trị giảm" value={form.discountValue} onChange={e=>setForm({...form,discountValue:e.target.value})}/><input required className="input-field" inputMode="numeric" placeholder="Đơn tối thiểu" value={form.minOrderValue} onChange={e=>setForm({...form,minOrderValue:e.target.value})}/><input className="input-field" inputMode="numeric" placeholder="Giảm tối đa" value={form.maxDiscount} onChange={e=>setForm({...form,maxDiscount:e.target.value})}/><input required type="date" className="input-field" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/><input required type="number" min="1" className="input-field" placeholder="Lượt dùng" value={form.usageLimit} onChange={e=>setForm({...form,usageLimit:e.target.value})}/></div><div style={{display:'flex',justifyContent:'flex-end',gap:10}}><button type="button" className="btn-secondary" onClick={()=>setShow(false)}>Hủy</button><button className="btn-primary">Tạo voucher</button></div></form></div>}</div>;
}